version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8081:80"
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "5000:5000"